# Generated by Django 5.0.4 on 2024-04-30 12:16

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=airport.models.airplane_image_file_path
            ),
        ),
    ]
